### ISSUE TITLE
Installation with plug?

### ISSUE THREAD

**Issue by at8i** [p00f/clangd_extensions.nvim#21] opened 2022-06-19 18:49 UTC
I have installed your plugin using plug manger in both Mac and arch but it is not working. The only problem would be plug installation.
Do i need to install it with packer?

**Comment by p00f** [comment] 2022-06-20 05:11
no

**Comment by at8i** [comment] 2022-06-20 07:19
`"lspconfig
Plug 'neovim/nvim-lspconfig'
Plug 'p00f/clangd_extensions.nvim'

function! DoRemote(arg)
  UpdateRemotePlugs
endfunction
call plug#end()

luafile ~/.config/nvim/lsp.lua
'
Lsp.lua:
'
-- Mappings.
local opts = { noremap=true, silent=true }
vim.keymap.set('n', '<space>e', vim.diagnostic.open_float, opts)
vim.keymap.set('n', '[d', vim.diagnostic.goto_prev, opts)
vim.keymap.set('n', ']d', vim.diagnostic.goto_next, opts)
vim.keymap.set('n', '<space>q', vim.diagnostic.setloclist, opts)

local on_attach = function(client, bufnr)
  vim.api.nvim_buf_set_option(bufnr, 'omnifunc', 'v:lua.vim.lsp.omnifunc')
  -- Mappings.
  local bufopts = { noremap=true, silent=true, buffer=bufnr }
  vim.keymap.set('n', 'gD', vim.lsp.buf.declaration, bufopts)
  vim.keymap.set('n', 'gd', vim.lsp.buf.definition, bufopts)
  vim.keymap.set('n', 'K', vim.lsp.buf.hover, bufopts)
  vim.keymap.set('n', 'gi', vim.lsp.buf.implementation, bufopts)
  vim.keymap.set('n', '<C-k>', vim.lsp.buf.signature_help, bufopts)
  vim.keymap.set('n', '<space>wa', vim.lsp.buf.add_workspace_folder, bufopts)
  vim.keymap.set('n', '<space>wr', vim.lsp.buf.remove_workspace_folder, bufopts)
  vim.keymap.set('n', '<space>wl', function()
    print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
  end, bufopts)
  vim.keymap.set('n', '<space>D', vim.lsp.buf.type_definition, bufopts)
  vim.keymap.set('n', '<space>rn', vim.lsp.buf.rename, bufopts)
  vim.keymap.set('n', '<space>ca', vim.lsp.buf.code_action, bufopts)
  vim.keymap.set('n', 'gr', vim.lsp.buf.references, bufopts)
  vim.keymap.set('n', '<space>f', vim.lsp.buf.formatting, bufopts)
end

local lsp_flags = {
  debounce_text_changes = 150,
}

require("clangd_extensions").setup {
    server = {
    on_attach = on_attach,
    flags = lsp_flags,
    },
}
'

At the top you can see the end of my Plug and as you can see I configure the plugin afterwards. But the problem is after installing the plugin I don't have access to your plugin's commands in my Command-line. for example when I enter ':Clangd' the only command available is 'ClandSwtitchSourceHeader' which comes from Lsp. Am I doing something wrong? I have many plugins working without any problems. I have looked everywhere  for reasons why a plugin commands cannot be recognised before coming here because this is really weird.

**Comment by p00f** [comment] 2022-06-20 07:46
the config looks correct

**Comment by p00f** [comment] 2022-06-20 07:47
Do you get inlay hints?

**Comment by at8i** [comment] 2022-06-20 08:27
No inlay hints. But I am pretty sure it is something from my side because it happens in MacOS and Arch. Clangd attaches to the buffer in LspInfo. My only guess is that I don't standard Lua file system. I am just trying Lua plugins to see they work. Should I create Lua folder and namespace and etc or is it something else?

**Comment by at8i** [comment] 2022-06-20 08:40
I installed support for node.js and it fixed everything. 
`npm install -g neovim` and it worked.

**Comment by p00f** [comment] 2022-06-20 12:54
That's not relevant, I don't even have nodejs...

![image](https://user-images.githubusercontent.com/36493671/174605944-93fb0d0b-e536-443d-89da-4f0169c5a8c5.png)

Anyway, closing since the issue is fixed

**Closed by p00f** 2022-06-20 12:54 UTC
